### ISSUE TITLE
V4 Roadmap

### ISSUE THREAD

**Issue by thekip** [lingui/js-lingui#1359]
Let's gather here tasks for new upcoming major release: 

- [x] Extractor: Don't use intermediate catalogs https://github.com/lingui/js-lingui/pull/1358 
- [x] Extractor: Change babel configuration approach, https://github.com/lingui/js-lingui/pull/1367 fixes:
    #1314 
    #1305
    #1206
    #952
- [x] Macro: Update public typings https://github.com/lingui/js-lingui/pull/1340 fixes: 
      #1288
      #1324 
      #1323
- [x] ~~Macro: https://github.com/lingui/js-lingui/issues/1361. This opens the possibility for new frameworks such as solid or qwik or vue. Also, properly fixes https://github.com/lingui/js-lingui/issues/936~~
- [x]  https://github.com/lingui/js-lingui/issues/1360  fixes: 
      https://github.com/lingui/js-lingui/issues/1198
- [x] deps tree Extractor. Support MPA apps (NextJS) and monorepos, https://github.com/lingui/js-lingui/pull/1469
- [x] Custom extractors, https://github.com/lingui/js-lingui/pull/1536
- [x] ~~Provide an automatic codemod for migration v3 -> v4.~~

I'n going to create a separate issues (or discussion) for each of the items in the list and elaborate more on how I see these changes. 

@Martin005 @andrii-bodnar what do you think about that?

**Comment by andrii-bodnar** [comment]
@thekip thank you! It's definitely great to have such a list 🚀 

We can collect these issues and start working on them when we'll be ready for a major release.

Releasing a major version is a huge commitment so it should be carefully planned and should happen when it really justified.

IMO, before that, we need to resolve non-breaking issues and stabilize the library as much as possible.

**Comment by thekip** [comment]
You have plans "somewhere" not in public field, nobody knows them.  Let's bring it to the public. 

What you mean by:

> we'll be ready for a major release.
> "stabilize"

Actually, this list here not because I have a lot of free time, but because I want to fix existing issues and bad design to be able to move forward. 
And all task in this list is about "stabilize". I don't understand what else you think should be "stabilized".

**Comment by andrii-bodnar** [comment]
> stabilize

I mean just reducing the number of current issues, as much as possible keeping it backward compatible

> we'll be ready for a major release

Saying that I meant when we're sure we won't have to do the next major release anytime soon after v4. Major releases are not a good thing for users, because they are always changes in the code, support from our side, etc.

But it's ok and I understand that it should happen. Just trying to avoid extra effort for users in switching versions.

> You have plans "somewhere" not in public field, nobody knows them. Let's bring it to the public.

The main plans for now:
- reducing the number of current issues as much as possible
- new documentation
- export to a new file format (this idea is still in draft and needs more investigation)

**Comment by thekip** [comment]
> reducing the number of current issues as much as possible

To fix most of the issues which appear every day, we need to introduce breaking changes. They would not be noticeable for most of the users but it's still breaking change which should bump a major version.

**Comment by Bertg** [comment]
A while ago I suggested in #1283 the following:

> Lingui (in production) produces code with translations baked in, basically a package per language, with 0 runtime impact.

Could this still be considered for v4? I understand it's a radical change, and probably requires a very different set of skills. I'm just wondering. If not would this be v5, or a "never"?

Could an other package build on top of v4 to make this possible, to opt-in to it?

**Comment by thekip** [comment]
@Bertg see https://github.com/lingui/js-lingui/issues/1384

**Comment by andrii-bodnar** [comment]
Created a milestone for related issues tracking - https://github.com/lingui/js-lingui/milestone/7
