### ISSUE TITLE
Support id and comment in `t` macro

### ISSUE THREAD

**Issue by tricoder42** [lingui/js-lingui#800]
This is often requested feature — `t` macro should accept custom `id` and/or `comment`. Using `defineMessage` in combination with `i18n._` is unnecessary verbose.

## Proposal

TLDR: Same api as `defineMessage`, but the output will be wrapped in `i18n._` as `t` and other macros does:

```
t({
  id: 'msgId,
  message: 'text'
})
// ↓ ↓ ↓ ↓ ↓ ↓
i18n._(/*i18n*/{ id: "msgId", values: { name }, message: 'text' })


t({
  id: 'msgId,
  message: 'text',
  comment: 'description for translators'
})
// ↓ ↓ ↓ ↓ ↓ ↓
i18n._(/*i18n*/{ id: "msgId", values: { name }, message: 'text', comment: 'description for translators' })


t({
  id: 'msgId,
  message: plural(value, { one: '...', other: '...' })
})

// ↓ ↓ ↓ ↓ ↓ ↓
i18n._(/*i18n*/{ id: "msgId", values: { name }, message: '{value, plural, one {...} other {...}' })

// Important! This should still work:
t`Hello World`
i18n._(/*i18n*/{ id: 'Hello World')
```

This should be fairly easy, because all logic for parsing messge descriptors is already inside `defineMessage` macro. It just needs an extra `if` in the right location, so the `t` macro can be used either as a template literal tag or a function.

## Tasks

- [x] update `t` macro in [`macroJs.ts`](https://github.com/lingui/js-lingui/blob/main/packages/macro/src/macroJs.ts#L213) to also accept message descriptor, the same way how `defineMessage` does
- [x] add tests to [`js-t.ts`](https://github.com/lingui/js-lingui/blob/main/packages/macro/test/js-t.ts) to cover new usecases
- [x] update `t` macro docs

Related issues: #797 #701
